### ISSUE TITLE
Design decisions around custom login handlers

### ISSUE THREAD

**Issue by willingham** [mkalioby/django-mfa2#25]
First off, thanks for making this project and the time you've put into it!  I'm looking at using and contributing to this project and had a couple of questions.  Specifically, I'm curious as to why a custom login function is used to check if MFA is activated as opposed to middleware?  Here's a specific example of middleware being used for MFA: https://github.com/MicroPyramid/django-mfa/blob/master/django_mfa/middleware.py.

**Comment by mkalioby** [comment]
Thank you for your great words.

To answer your question,  I did this for 2 reasons 

- currently we don't log the user in except after MFA (better security)
-  WebAuthn should be passwordless so the login flow should be changed

Finally the first project I integrated this with wasn't build on django authen so that way gave us freedom

The correct way is creating a **new authentication** backend, i may start looking into it

**Comment by mkalioby** [comment]
Closed due to inactivity
