### ISSUE TITLE
New feature: Change success link and url

### ISSUE THREAD

**Issue by mkalioby** [mkalioby/django-mfa2#48]
@Sirneij: I created new settings parameters to change the link when the keys are successfully registered, the names of parameters are 
* `MFA_REDIRECT_AFTER_REGISTRATION` which takes a view name.
* `MFA_SUCCESS_REGISTRATION_MSG` which defines the message

please test using version 2.2.0b2 which can be downloaded by

`pip install django-mfa2==2.2.0b2`

Waiting to hear from you.

**Comment by Sirneij** [comment]
Wow! This is good. Let me bootstrap a project to utilize these features.
I will give feedback here as soon as I get it up and running.

Feature suggestion:

Since we need to log user in before creating keys for them during registration, won't it be nice to remove such user from the database in case keys creation fails? Same scenario can also be applied to login. If keys verification during authentication fails, user should be logged out. 

These features might be made optional since some use cases might not need them.

**Comment by Sirneij** [comment]
Oh, that's great! I'll keep you posted. Let me try those features out.

**Comment by Sirneij** [comment]
THis

> @Sirneij: I created new settings parameters to change the link when the keys are successfully registered, the names of parameters are
> 
> * `MFA_REDIRECT_AFTER_REGISTRATION` which takes a view name.
> * `MFA_SUCCESS_REGISTRATION_MSG` which defines the message
> 
> please test using version 2.2.0b2 which can be downloaded by
> 
> `pip install django-mfa2==2.2.0b2`
> 
> Waiting to hear from you.


This has been tested and works well. It's live on [https://django-mfa2-example.herokuapp.com/](https://django-mfa2-example.herokuapp.com/) and this addition can be seen [here](https://github.com/Sirneij/django_mfa2_example/blob/19c42914dcf1b8be518982767f9045a87b0a67d4/django_mfa2_example/settings.py#L157)

**Comment by mkalioby** [comment]
Thanks alot, will release it soon.

**Comment by Sirneij** [comment]
Okay... I will be on a lookout for it. I am even thinking of writing a comprehensive article on building a fingerprint-based authentication system using this library. Such articles are very scarce.

**Comment by mkalioby** [comment]
Sure, that will be great.

**Comment by Sirneij** [comment]
Is there a way we could add the normal app's navigation bar to the security pages of FIDO?

**Comment by mkalioby** [comment]
Sure, the app extends your template, check the documentation.

**Comment by mkalioby** [comment]
V2.2.0 has been released
